// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CreateRoomReducer from "../create_room_reducer";
import EndGameReducer from "../end_game_reducer";
import EndTurnReducer from "../end_turn_reducer";
import JoinAsSpectatorReducer from "../join_as_spectator_reducer";
import JoinRoomReducer from "../join_room_reducer";
import LeaveRoomReducer from "../leave_room_reducer";
import StartGameReducer from "../start_game_reducer";
import UpdateGameStateReducer from "../update_game_state_reducer";
import UpdateScoreReducer from "../update_score_reducer";

export type CreateRoomParams = __Infer<typeof CreateRoomReducer>;
export type EndGameParams = __Infer<typeof EndGameReducer>;
export type EndTurnParams = __Infer<typeof EndTurnReducer>;
export type JoinAsSpectatorParams = __Infer<typeof JoinAsSpectatorReducer>;
export type JoinRoomParams = __Infer<typeof JoinRoomReducer>;
export type LeaveRoomParams = __Infer<typeof LeaveRoomReducer>;
export type StartGameParams = __Infer<typeof StartGameReducer>;
export type UpdateGameStateParams = __Infer<typeof UpdateGameStateReducer>;
export type UpdateScoreParams = __Infer<typeof UpdateScoreReducer>;

