// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const GameStates = __t.object("GameStates", {
  roomId: __t.u32(),
  stateJson: __t.string(),
  currentTurn: __t.u32(),
  turnNumber: __t.u32(),
});
export type GameStates = __Infer<typeof GameStates>;

export const Players = __t.object("Players", {
  identity: __t.identity(),
  roomId: __t.u32(),
  displayName: __t.string(),
  isHost: __t.bool(),
  playerNumber: __t.u32(),
  score: __t.u32(),
  isSpectator: __t.bool(),
});
export type Players = __Infer<typeof Players>;

export const Rooms = __t.object("Rooms", {
  id: __t.u32(),
  gameType: __t.string(),
  status: __t.string(),
  maxPlayers: __t.u32(),
  createdBy: __t.identity(),
});
export type Rooms = __Infer<typeof Rooms>;

